name: nixidy action
description: Generate manifest for a nixidy environment

inputs:
  environment:
    description: Name of the environment to build
    required: true
  cwd:
    description: Path to directory containing the checked out repository
    default: '.'
  pr:
    description: Whether or not to make a PR for the promotion
    default: 'false'
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{github.token}}

runs:
  using: composite
  steps:
    - shell: bash
      env:
        FLAKE: github:${{github.action_repository}}/${{github.action_ref}}
        DEST_DIR: ${{runner.temp}}/${{inputs.environment}}
      run: |
        TARGET_BRANCH=$(nix run '${{env.FLAKE}}#' -- info '${{inputs.cwd}}#${{inputs.environment}}' --json | jq -r .branch)
        PR_BRANCH="promote/$TARGET_BRANCH"

        if git -C "${{inputs.cwd}}" fetch origin "$TARGET_BRANCH"; then
          git -C "${{inputs.cwd}}" worktree add --checkout "${{env.DEST_DIR}}" "$TARGET_BRANCH"
         else
          git -C "${{inputs.cwd}}" worktree add --orphan -b "$TARGET_BRANCH" "${{env.DEST_DIR}}"
        fi

        RESULT=$(nix run '${{env.FLAKE}}#' -- build '${{inputs.cwd}}#${{inputs.environment}}' --print-out-paths --no-link)

        rsync --recursive --delete --exclude=.git -L "$RESULT/" "${{env.DEST_DIR}}"

        if [[ "${{inputs.pr}}" == "true" ]]; then
          git -C "${{env.DEST_DIR}}" checkout -B "$PR_BRANCH"
          echo "BRANCH=$PR_BRANCH" >> "$GITHUB_ENV"
          echo "FORCE=--force" >> "$GITHUB_ENV"
        else
          echo "BRANCH=$TARGET_BRANCH" >> "$GITHUB_ENV"
          echo "FORCE=" >> "$GITHUB_ENV"
        fi

        echo "TARGET_BRANCH=$TARGET_BRANCH" >> "$GITHUB_ENV"
        echo "DEST_DIR=$(realpath --relative-to "$PWD" "$DEST_DIR")" >> "$GITHUB_ENV"
        echo "COMMIT_MESSAGE=chore(${{inputs.environment}}): promote to ${{inputs.environment}} ${{github.sha}}" >> "$GITHUB_ENV"

    - uses: EndBug/add-and-commit@v9
      with:
        cwd: ${{env.DEST_DIR}}
        default_author: github_actions
        message: ${{env.COMMIT_MESSAGE}}
        fetch: false
        push: --set-upstream origin ${{env.BRANCH}} ${{env.FORCE}}

    - uses: thomaseizinger/create-pull-request@1.4.0
      if: inputs.pr == 'true'
      with:
        github_token: ${{inputs.token}}
        head: ${{env.BRANCH}}
        base: ${{env.TARGET_BRANCH}}
        title: ${{env.COMMIT_MESSAGE}}
