name: CLI shellcheck test

on:
  push:
    branches:
      - main
    paths:
      - nixidy/**
  pull_request:
    branches:
      - main
    paths:
      - nixidy/**

jobs:
  static-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - name: Run statix
      run: |
        echo "# Test Results" > $GITHUB_STEP_SUMMARY
        nix run .#cliTest | tee -a $GITHUB_STEP_SUMMARY
