name: CLI shellcheck test

on:
  push:
    branches:
      - main
    paths:
      - nixidy/**
  pull_request:
    branches:
      - main
    paths:
      - nixidy/**

jobs:
  static-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Run statix
      run: |
        nix run .#cliTest
