name: crd2jsonschema unit tests

on:
  push:
    branches:
      - main
    paths:
      - pkgs/generators/crd2jsonschema.py
  pull_request:
    branches:
      - main
    paths:
      - pkgs/generators/crd2jsonschema.py

jobs:
  crd2jsonschema-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - name: Run crd2jsonschema unit tests
      shell: bash
      run: |
        echo "# Test Results" > $GITHUB_STEP_SUMMARY
        nix run .#crd2jsonschemaTest | tee -a $GITHUB_STEP_SUMMARY
