name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v11

    - run: |
        nix-build ./docs -A html --out-link public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
