name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - run: |
        nix build .#docs.html --out-link public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
