name: Statix check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - name: Run statix
      run: |
        nix run .#staticCheck

    - name: Check formatting
      run: |
        nix fmt
        if ! git diff --exit-code; then
          echo "Code is not formatted properly. Please run 'nix fmt' and commit the changes."
          exit 1
        fi
