name: Unit testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - manifests/**
  pull_request:
    branches:
      - main

jobs:
  lib-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Run .#libTests
      run: |
        echo "# Test Results" > $GITHUB_STEP_SUMMARY
        nix run .#libTests | tee -a $GITHUB_STEP_SUMMARY

  module-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Run .#moduleTests
      run: |
        echo "# Test Results" > $GITHUB_STEP_SUMMARY
        nix run .#moduleTests | tee -a $GITHUB_STEP_SUMMARY
