name: Unit testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - manifests/**
  pull_request:
    branches:
      - main

jobs:
  lib-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Run statix
      run: |
        nix run .#libTests

  module-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Run statix
      run: |
        nix run .#moduleTests
